### ISSUE TITLE
yaml_to_form 组件的设计

### ISSUE THREAD

**Issue by fushang318** [mindpin/task-page#2]
# 参考 yaml

https://github.com/mindpin/briefing/issues/44
# 组件介绍

目前团队协作工具记录的数据，数据格式正在探索阶段，所以数据格式可能会比较频繁的修改，基于这个需求我们开发一个组件，这个组件可以

1 通过yaml 格式生成页面的多个表单，方便录入
2 页面的多个表单提交的数据，会汇总成yaml保存到数据表的一个字段
3 可以把数据表中保存的yaml生成页面的HTML，方便友好的显示
# 封装形式

封装成一个 gem,方便 rails 项目使用
# 设想的使用方式
## 增加配置文件

config/initialize/yaml_to_form.rb

``` ruby
YamlToForm.config do
  rule :task_record do
    date format: :time, validates: {presence: true}
    members format: :array do
      name format: :string
      begin format: :array do
        thread format: :string
        items format: :array do
          desc format: :text
          priority format: :integer
          willbedone format: :boolean
          timealloc  format: :integer
        end
      end
      _end format: :array do
        thread format: :string
        items format: :array do
          desc format: :text
          isdone format: :boolean
          reason format: :text
          timeused  format: :integer
          submits format: :array do
            name format: :string
            link format: :string
            comment format :text
            note format :text
          end
        end
      end
    end
  end
end
```
## 模型使用

``` ruby
class Task
  include Mongoid::Document
  include Mongoid::Timestamps

  include YamlToForm::RecordMethods

  use_rule :task_record
end


task = Task.new
# task 通过 use_rule 方法使用了 task_record 这个配置
# rule_yaml 对象可以直接读取对应的数据

# 读取 yaml
task.rule_yaml_raw

# 读取 yaml 中的 date,并且转换成了 Time 类型
task.rule_yaml.date

# 读取 yaml 中的 members 数组内第一个元素的 name,并且转换成了 String 类型
task.rule_yaml.members[0].name
```
## 生成 form

``` haml
  = form_tag "/tasks" do
    = YamlToForm.input(Task)
    = submit "提交"
```
## controler action

``` ruby
  def create
    # gem 需要使用 middleware 把 YamlToForm.input(Task) 生成的多个 input params
    # 合并成 yaml 放到 params[:task][:rule_yaml_raw]
    # 方便这里使用
    params[:task][:rule_yaml_raw]
  end
```
## show 页面中的 rule_yaml_raw 的显示

```
  # 组织成简单的 html 显示在show页面上
  task.rule_yaml_html
```

**以上是目前可以想到的。**
**但是更细节的东西，比如如何通过配置自定义生成form的模板，目前考虑不清楚，不过这些细节可以等初版效果有了以后再慢慢扩充**

**Comment by fushang318** [comment]
**经过讨论，第三稿设计**

# 封装形式

纯 js 组件

# 设想的使用方法

__配置文件用 yaml __

## 示例

http://host/config/xxx.yaml

``` yaml
date:
  format: time
  validates:
    presence: true
members:
  format: array
  value:
    name:
      format: string
    begin:
      format: array
      value:
        thread:
          format: string
        items:
          format: array
          value:
            desc:
              format: text
            priority:
              format: integer
            willbedone:
              format: boolean
            timealloc: 3
              format: integer
    end:
      format: array
      value:
        thread:
          format: string
        items:
          format: array
          value:
            desc:
              format: string
            isdone:
              format: boolean
            timeused:
              format: integer
            submits:
              format: array
              value:
                name:
                  format: string
                link:
                  format: string
                comment:
                  format: text
                note:
                  format: text
```

``` html
<script src="jquery.js"/>
<script src="yaml_to_form.js"/>
<script>
  <!-- 
    ajax 请求 http://host/config/xxx.yaml 静态文件，不能跨域
  -->
  YamlToForm.load_config("/config/xxx.yaml")
</script>

<body>
  <form action="/xx" method="post">
    <!-- 
      组件的js会遍历页面上 input[data-rel="yaml_to_form"] 的元素
      根据自定义的配置生成表单，并同步表单的数据生成yaml复制到该 input
    -->
    <input type="text" name="yaml" data-rel="yaml_to_form"/>
    <input type="submit" value="提交"/>
  </form>
</body>
```

**Comment by ben7th** [comment]
我设想的使用方法：

HTML

``` html
<body>
  <div class='container'></div>
  <a class='submit'></a>

  <script src="jquery.js"/>
  <script src="yaml_to_form.js"/>
</body>
```

COFFEE

``` coffeescript
jQuery ->
  YamlToForm.load_config "/xxx/xxx/xxx.yaml", (ytf)->
    # 在指定的 dom 中，构建带有复杂交互的输入组件
    instance = ytf.render_to jQuery('.container')

    # 绑定提交按钮事件
    jQuery('a.submit').click ->
      yaml_string = instance.get_string()
      jQuery.ajax
         url: '....'
         data:
            ......
```

**Comment by fushang318** [comment]
**经过讨论，最终设计**

# 封装形式

纯 js 组件

# 设想的使用方法

**配置文件用 yaml**

## 示例

http://host/config/xxx.yaml

``` yaml
date: time(*)
members: 
  - name: string
    begin: 
      - thread: string
        items: 
          - desc: text
            priority: integer
            willbedone: boolean
            timealloc: integer
    end:
      - thread: string
        items:
          - desc: string
            isdone: boolean
            timeused: integer
            submits:
              - name: string
                link: string
                comment: text
                note: text
```

HTML

``` html
<body>
  <div class='container'></div>
  <a class='submit'></a>

  <script src="jquery.js"/>
  <script src="yaml_to_form.js"/>
</body>
```

COFFEE

``` coffeescript
jQuery ->
  YamlToForm.load_config "/xxx/xxx/xxx.yaml", (ytf)->
    # 在指定的 dom 中，构建带有复杂交互的输入组件
    instance = ytf.render_to jQuery('.container')

    # 绑定提交按钮事件
    jQuery('a.submit').click ->
      yaml_string = instance.get_string()
      jQuery.ajax
         url: '....'
         data:
            ......
```
